-- Legacy password hashes are preserved in public.wabi_legacy_users by schema.sql.
-- This file intentionally performs no deletion: public.wabi_users now stores
-- Supabase Auth-backed application accounts.
